# Generated by Django 3.2.16 on 2025-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default=True, max_length=20, verbose_name='Название'),
        ),
    ]
