# Generated by Django 3.2.16 on 2025-01-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Название', max_length=20, verbose_name='Название'),
        ),
    ]
