# Generated by Django 3.2.16 on 2025-01-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250111_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=20, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipes',
            field=models.TextField(max_length=250, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
