# Generated by Django 3.2.16 on 2025-01-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250112_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipes',
            field=models.TextField(verbose_name='Рецепт'),
        ),
    ]
